### ISSUE TITLE
Remove acronyms

### ISSUE THREAD

**Issue by IanaKhitsko** [fandeath/theGame#1]
https://github.com/fandeath/theGame/blob/a8b1903725eb08c474c90d92bbf3756f2c465f6c/The%20Game%202.py#L5
 Can we use here deltaRow, deltaCol, row, col ?

**Comment by fandeath** [comment]
Yes, we can replace `dr` and `dc` with `deltaRow` and `deltaCol` respectively to improve code readability. However, `row` and `col` are already being used to store the starting position, so it's better not to use these variable names in this case.
