### ISSUE TITLE
Magic const

### ISSUE THREAD

**Issue by IanaKhitsko** [fandeath/theGame#2]
https://github.com/fandeath/theGame/blob/a8b1903725eb08c474c90d92bbf3756f2c465f6c/The%20Game%202.py#L9

19 can be const

**Comment by IanaKhitsko** [comment]
the same as 5

**Comment by fandeath** [comment]
Yes, you're right. We can define constants `BOARD_SIZE` with a value of 19 and `WIN_LENGTH` with a value of 5, and then use them instead of numbers in the code. This will improve readability and facilitate future changes if the board size or the winning sequence length changes.
