### ISSUE TITLE
Tie issue

### ISSUE THREAD

**Issue by tiwatit** [fandeath/theGame#5]
https://github.com/fandeath/theGame/blob/4d8f226253bf159d3a6ce2a522249724745f7b60/The%20Game%202.py#L93
Consider adding a comment or a print statement to indicate when a tie occurs, as the current code only prints "Нічия!" after all test cases have been processed.

**Comment by fandeath** [comment]
After the loop that checks the game board for a winning combination, a check was added for the tie variable. If tie is True, it means that there are no winning combinations on the board, and the game ended in a tie. In this case, the message "Нічия!" (Tie!) is printed.
